### ISSUE TITLE
EPEL 10 "minor" release breaks fedora-all alias

### ISSUE THREAD

**Issue by praiskup** [rpm-software-management/fedora-distro-aliases#19] opened 2024-08-15 09:40 UTC
The `tito release` now failed for me with this config:

```
[fedora-git-all]
releaser = tito.release.FedoraGitReleaser
branches = fedora-all epel10 epel9 epel8
```
Traceback:
```
Creating output directory: /tmp/tito
Will release to the following targets: fedora-git-all
Releasing to target: fedora-git-all
Checking for tag [mock-core-configs-41.1-1] in git repo [https://github.com/rpm-software-management/mock.git]
Working in: /tmp/tito/release-mock-core-configstqqs1rpy
Traceback (most recent call last):
  File "/usr/bin/tito", line 33, in <module>
    sys.exit(load_entry_point('tito==0.6.26', 'console_scripts', 'tito')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/tito/cli.py", line 944, in main
    CLI().main(sys.argv[1:])
  File "/usr/lib/python3.12/site-packages/tito/cli.py", line 210, in main
    return module.main(argv)
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/tito/cli.py", line 635, in main
    releaser = releaser_class(
               ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/tito/release/distgit.py", line 66, in __init__
    self.git_branches = self._branches()
                        ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/tito/release/distgit.py", line 111, in _branches
    aliases = get_distro_aliases()
              ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/fedora_distro_aliases/__init__.py", line 36, in get_distro_aliases
    distros.sort(key=lambda x: int(x.version))
  File "/usr/lib/python3.12/site-packages/fedora_distro_aliases/__init__.py", line 36, in <lambda>
    distros.sort(key=lambda x: int(x.version))
                               ^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '10.0'
```

**Comment by xsuchy** [comment] 2024-08-16 12:38
Duplicate of https://github.com/rpm-software-management/fedora-distro-aliases/issues/17

**Closed as completed** 2024-08-16 12:39 UTC

**Comment by FrostyX** [comment] 2024-08-19 10:20
I will do a new release to get the fix into Fedora.
